INSERT INTO SOandPI
	(Outcome, Indicator)
    VALUES
    ('a','Students understand the foundations of math, logic, and statistics.'),
    ('a','Students can apply this knowledge to algorithm development.'),
    ('a','Students can apply this knowledge to data analysis.'),
    ('b','Students are able to formulate and decompose a problem into appropriate components.'),
    ('b','Students are able to soljoinsotopiicit and formulate software and hardware requirements specifications.'),
    ('b','Students are able to estimate resources required for the proposed solution.'),
    ('c','Ability to Conceptualize.'),
    ('c','Ability to Develop.'),
    ('c','Ability to Validate.'),
    ('d','Organization and Responsibilities.'),
    ('d','Interaction'),
    ('d','Productivity'),
    ('e','Students will demonstrate understanding of intellectual property issues.'),
    ('e','Students will demonstrate working knowledge of a code of ethics.'),
    ('e','Students value fairness in making judgments involving discrimination between people and groups.'),
    ('e','Students appreciate the need for proper etiquette and proactive social behavior in professional situations.'),
    ('f','Preparing Documents and Presentation Materials.'),
    ('f','Presentation Delivery.'),
    ('g','Students will demonstrate understanding of various ways in which computing technology impacts individuals, organizations, and society.'),
    ('g','Students will demonstrate ability to analyze and reason about the impact of advances in computer technology.'),
    ('g','Students will demonstrate an understanding of the responsibilities of a computing technology professional with respect to individuals and society.'),
    ('h','Students will demonstrate recognition of the need for continuing professional development.'),
    ('h','Students will demonstrate familiarity with means for continuing professional development.'),
    ('h','Students will demonstrate ability to independently identify and assimilate new information.'),
    ('h','Students will demonstrate an ability to criticize and evaluate the quality of new information.'),
    ('i','Ability to do task-specific research to learn new techniques, skills, and tools.'),
    ('i','Students will demonstrate competence with multiple current platforms for computing and development.'),
    ('i','Students will demonstrate competence with a selected set of tools (defined in cooperation with advisory board.'),
    ('j','Ability to identify and evaluate relevance of new technicl concepts and practices in the core information technologies.'),
    ('j','Students will understand and be able to apply current technical concepts and practices in the core information technologies.'),
    ('k','Students will demonstrate competence in the process of understanding and formally specifying user requirements.'),
    ('k','Students will demonstrate use of tools for modeling user needs.'),
    ('k','Students will demonstrate ability to develop software from user requirements.'),
    ('l','Students will demonstrate knowledge of current IT solutions.'),
    ('l','Students will demonstrate ability to collect user requirements and recognize failures in existing IT solutions.'),
    ('l','Students can apply knowledge of current technologies to integrate solutions.'),
    ('m','Demonstrate knowledge of current standards and their application.');